language: cpp

sudo: false

addons:
  apt:
    packages:
    - libfftw3-3
    - libfftw3-dev

compiler: gcc

env: ITK_VERSION=v4.10.0

cache:
  directories:
  - /home/travis/itk-v4.2.0
  - /home/travis/itk-v4.2.0-build
  - /home/travis/itk-v4.10.0
  - /home/travis/itk-v4.10.0-build

before_script:
  - export NUM_THREADS=4
  - export ITK_SOURCE_DIR=/home/travis/external/itk-${ITK_VERSION}
  - export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
  - if ! test -d ${ITK_SOURCE_DIR}; then git clone --branch ${ITK_VERSION} git://itk.org/ITK.git ${ITK_SOURCE_DIR}; fi
  - if ! test -d ${ITK_BUILD_DIR}; then mkdir ${ITK_BUILD_DIR}; fi
  - cd ${ITK_BUILD_DIR}
  - cmake ${ITK_SOURCE_DIR}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TESTING=OFF
    -DModule_ITKReview=ON
    -DITK_USE_FFTWD=ON
    -DITK_USE_FFTWF=ON
    -DITK_USE_SYSTEM_FFTW=ON
    -DUSE_FFTWD=ON
    -DUSE_FFTWF=ON
    -DUSE_SYSTEM_FFTW=ON
  - make --jobs=$NUM_THREADS --keep-going
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make --jobs=$NUM_THREADS --keep-going all test

