platform:
  - x64

configuration:
  - Release

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  ITK_VERSION: v4.12.0
  global:
    CYG_ROOT: C:\cygwin

  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"

cache:
  - 'C:/projects/ITK'
  - 'C:/projects/ITK-build'

before_build:
  - if not exist "C:/projects/ITK" (
      cd C:/projects/ &
      git clone --depth 1 --branch %ITK_VERSION% https://github.com/InsightSoftwareConsortium/ITK.git ITK &
      cd C:/projects/%APPVEYOR_BUILD_FOLDER%
    )
  - if not exist "C:/projects/ITK-build" (
      cd C:/projects/ &
      mkdir ITK-build & cd ITK-build & cmake -G "%GENERATOR%" -DBUILD_TESTING:BOOL=OFF ../ITK & cmake --build . &
      cd C:/projects/%APPVEYOR_BUILD_FOLDER%
    )

build_script:
  - mkdir build & cd build & cmake -G "%GENERATOR%" -DITK_DIR="C:/projects/ITK-build" .. & cmake --build .

test: off

deploy: off
